import { AppSettings } from "./types";

export const APP_NAME = "超强振幅";

export const DEFAULT_SETTINGS: AppSettings = {
  appName: APP_NAME,
  accounts: [
    {
      id: "main",
      name: "double",
      enabled: true,
      isMasterAccount: true,
      binance: {
        apiKey: "uBOX5sM6iJ8KBVdxcKhHmc75tDHisbxgRqaacR1aPKMpLegDpR4Al4fe44gpPb1Q",
        secretKey: "ujb5lLEDnkbOvfxwnevQXyDbR14lysO7rW8r2r51c0HFmc0QmYtPFdX7RbCuF66a",
        baseUrl: "https://fapi.binance.com",
        wsUrl: "wss://fstream.binance.com/ws",
      },
      scanner: {
        stage0: {
          interval: "1h",
          startTime: "00:06:00.000",
          klinePeriod: "15m",
          minKlines: 300,
          maxKlines: 115000,
          includeTradFi: false,
        },
        stage0P: {
          enabled: true,
          interval: "15m",
          startTime: "00:07:36.000",
          periods: {
            "15m": { enabled: false, count: 7, threshold: -3 },
          },
          abnormalMove: {
            enabled: false,
            lookbackHours: 10,
            windowMinutes: 60,
            maxPump: 25,
            maxDrop: 30,
          }
        },
        stage1: {
          interval: "15m",
          startTime: "00:13:54.300",
          minVolumeM1: 500000,
          priceChangeK1: [-100, 100],
          whitelist: [],
          blacklist: [],
        },
        stage2: {
          enabled: true,
          interval: "15m",
          startTime: "00:14:59.300",
          cooldown: 0,
          preferredMode: 'volume',
          amplitudeMode: 'bottomHigh',
          conditions: {
            amp: { enabled: true, range: [10, 30] },
            longShort: { enabled: true, buyEnabled: true, buy: 80, sellEnabled: true, sell: 20 },
            m: { enabled: true, range: [2980000, 1000000000] },
            fundingRateOptimization: { enabled: true, windowMinutes: 5, shortThreshold: -0.3 },
          },
          singleK: {
            enabled: false,
            preferredMode: 'volume',
            k2: { enabled: true, range: [4, 9] },
            a: { enabled: true, range: [0, 3], mode: 'fixed' },
            m: { enabled: true, range: [6980000, 1000000000] },
            k2Sell: { enabled: true, range: [4, 9] },
            aSell: { enabled: true, range: [0, 3], mode: 'fixed' },
            mSell: { enabled: true, range: [6980000, 1000000000] },
            fundingRateOptimizationSell: { enabled: true, windowMinutes: 5, shortThreshold: -0.3 }
          },
        },
        timeControl: {
          enabled: true,
          hours: Array(24).fill(true),
          mode: '+2',
        },
      },
      order: {
        leverage: 5,
        positionRatio: 40,
        maxPosition: 40000,
        tpModeBuy: 'amp',
        tpModeSell: 'amp',
        tpRatioBuy: 42,
        tpRatioSell: 42,
        tpFixedBuy: 2,
        tpFixedSell: 2,
        tpAmpBuy: 20,
        tpAmpSell: 20,
        tpEnabled: true,
        tpBuyEnabled: true,
        tpSellEnabled: true,
        slModeBuy: 'fixed',
        slModeSell: 'fixed',
        slRatioBuy: 85,
        slRatioSell: 85,
        slFixedBuy: 20,
        slFixedSell: 20,
        slAmpBuy: 85,
        slAmpSell: 85,
        slEnabled: true,
        slBuyEnabled: true,
        slSellEnabled: true,
        mLinkEnabled: false,
        mLinkValue: 1800,
        singleKMLinkEnabled: false,
        singleKMLinkValue: 1800,
        singleKTpEnabled: true,
        singleKTpModeBuy: 'amp',
        singleKTpModeSell: 'amp',
        singleKTpBuyEnabled: true,
        singleKTpSellEnabled: true,
        singleKTpRatioBuy: 25,
        singleKTpRatioSell: 25,
        singleKTpFixedBuy: 2,
        singleKTpFixedSell: 2,
        singleKTpAmpBuy: 25,
        singleKTpAmpSell: 25,
        singleKSlEnabled: true,
        singleKSlModeBuy: 'fixed',
        singleKSlModeSell: 'fixed',
        singleKSlBuyEnabled: true,
        singleKSlSellEnabled: true,
        singleKSlRatioBuy: 20,
        singleKSlRatioSell: 20,
        singleKSlFixedBuy: 20,
        singleKSlFixedSell: 20,
        singleKSlAmpBuy: 20,
        singleKSlAmpSell: 20,
        positiveWindow: 0.7,
        maxHoldTime: 14.9,
        kBestPeriod: "15m",
        kBestWindow: [1, 5],
        tpSlCalcMode: "closedK",
        preferredOrderCount: 2,
        secondOrderCustomEnabled: false,
        secondLeverage: 5,
        secondPositionRatio: 40,
        secondMaxPosition: 40000,
        secondMaxHoldTime: 14.9,
        secondMLinkEnabled: false,
        secondMLinkValue: 1800,
        secondTpEnabled: true,
        secondTpModeBuy: "ratio",
        secondTpModeSell: "ratio",
        secondTpBuyEnabled: true,
        secondTpSellEnabled: true,
        secondTpRatioBuy: 42,
        secondTpRatioSell: 42,
        secondTpFixedBuy: 2,
        secondTpFixedSell: 2,
        secondTpAmpBuy: 25,
        secondTpAmpSell: 25,
        secondSlEnabled: true,
        secondSlModeBuy: "ratio",
        secondSlModeSell: "ratio",
        secondSlBuyEnabled: true,
        secondSlSellEnabled: true,
        secondSlRatioBuy: 85,
        secondSlRatioSell: 85,
        secondSlFixedBuy: 20,
        secondSlFixedSell: 20,
        secondSlAmpBuy: 85,
        secondSlAmpSell: 85,
        secondSingleKMLinkEnabled: false,
        secondSingleKMLinkValue: 1800,
        secondSingleKTpEnabled: true,
        secondSingleKTpModeBuy: 'amp',
        secondSingleKTpModeSell: 'amp',
        secondSingleKTpBuyEnabled: true,
        secondSingleKTpSellEnabled: true,
        secondSingleKTpRatioBuy: 25,
        secondSingleKTpRatioSell: 25,
        secondSingleKTpFixedBuy: 2,
        secondSingleKTpFixedSell: 2,
        secondSingleKTpAmpBuy: 25,
        secondSingleKTpAmpSell: 25,
        secondSingleKSlEnabled: true,
        secondSingleKSlModeBuy: 'fixed',
        secondSingleKSlModeSell: 'fixed',
        secondSingleKSlBuyEnabled: true,
        secondSingleKSlSellEnabled: true,
        secondSingleKSlRatioBuy: 20,
        secondSingleKSlRatioSell: 20,
        secondSingleKSlFixedBuy: 20,
        secondSingleKSlFixedSell: 20,
        secondSingleKSlAmpBuy: 20,
        secondSingleKSlAmpSell: 20,
      },
      withdrawal: {
        withdrawalThreshold: 518,
        retentionThreshold: 488,
        alarmThreshold: 5,
      },
    },
    {
      id: "1",
      name: "buy10",
      enabled: true,
      isMasterAccount: false,
      binance: {
        apiKey: "WFfz4vWCElGYqMuMM6NTnTLFIdtfK8tsvqF40iTYJFKRr7pHotw36meyu8aRy4sc",
        secretKey: "5admozRhof1nJdVZe5RiUTqtxMD9LWjUfjSCJwYHdn2AghuSFLexFRCmaqvU9iZk",
        baseUrl: "https://fapi.binance.com",
        wsUrl: "wss://fstream.binance.com/ws",
      },
      scanner: {
        stage0: {
          interval: "1h",
          startTime: "00:21:00.000",
          klinePeriod: "15m",
          minKlines: 300,
          maxKlines: 115000,
          includeTradFi: false,
        },
        stage0P: {
          enabled: false,
          interval: "15m",
          startTime: "00:10:16.000",
          periods: {
            "15m": { enabled: false, count: 7, threshold: -3 },
          },
          abnormalMove: {
            enabled: false,
            lookbackHours: 10,
            windowMinutes: 60,
            maxPump: 25,
            maxDrop: 30,
          }
        },
        stage1: {
          interval: "15m",
          startTime: "00:14:51.600",
          minVolumeM1: 500000,
          priceChangeK1: [-100, 100],
          whitelist: [],
          blacklist: [],
        },
        stage2: {
          enabled: true,
          interval: "15m",
          startTime: "00:14:59.600",
          cooldown: 0,
          preferredMode: 'amp',
          amplitudeMode: 'bottomHigh',
          conditions: {
            amp: { enabled: true, range: [10, 30] },
            longShort: { enabled: true, buyEnabled: true, buy: 80, sellEnabled: false, sell: 20 },
            m: { enabled: true, range: [2980000, 1000000000] },
            fundingRateOptimization: { enabled: true, windowMinutes: 5, shortThreshold: -0.3 },
          },
          singleK: {
            enabled: false,
            preferredMode: 'volume',
            k2: { enabled: true, range: [4, 9] },
            a: { enabled: true, range: [0, 3], mode: 'fixed' },
            m: { enabled: true, range: [6980000, 1000000000] },
            k2Sell: { enabled: true, range: [4, 9] },
            aSell: { enabled: true, range: [0, 3], mode: 'fixed' },
            mSell: { enabled: true, range: [6980000, 1000000000] },
            fundingRateOptimizationSell: { enabled: true, windowMinutes: 5, shortThreshold: -0.3 }
          },
        },
        timeControl: {
          enabled: true,
          hours: Array(24).fill(true),
          mode: '+2',
        },
      },
      order: {
        leverage: 5,
        positionRatio: 40,
        maxPosition: 40000,
        tpModeBuy: 'amp',
        tpModeSell: 'amp',
        tpRatioBuy: 44,
        tpRatioSell: 44,
        tpFixedBuy: 2,
        tpFixedSell: 2,
        tpAmpBuy: 25,
        tpAmpSell: 25,
        tpEnabled: true,
        tpBuyEnabled: true,
        tpSellEnabled: true,
        slModeBuy: 'fixed',
        slModeSell: 'fixed',
        slRatioBuy: 85,
        slRatioSell: 85,
        slFixedBuy: 20,
        slFixedSell: 20,
        slAmpBuy: 85,
        slAmpSell: 85,
        slEnabled: true,
        slBuyEnabled: true,
        slSellEnabled: true,
        mLinkEnabled: false,
        mLinkValue: 1800,
        singleKMLinkEnabled: false,
        singleKMLinkValue: 1800,
        singleKTpEnabled: true,
        singleKTpModeBuy: 'amp',
        singleKTpModeSell: 'amp',
        singleKTpBuyEnabled: true,
        singleKTpSellEnabled: true,
        singleKTpRatioBuy: 25,
        singleKTpRatioSell: 25,
        singleKTpFixedBuy: 2,
        singleKTpFixedSell: 2,
        singleKTpAmpBuy: 25,
        singleKTpAmpSell: 25,
        singleKSlEnabled: true,
        singleKSlModeBuy: 'fixed',
        singleKSlModeSell: 'fixed',
        singleKSlBuyEnabled: true,
        singleKSlSellEnabled: true,
        singleKSlRatioBuy: 20,
        singleKSlRatioSell: 20,
        singleKSlFixedBuy: 20,
        singleKSlFixedSell: 20,
        singleKSlAmpBuy: 20,
        singleKSlAmpSell: 20,
        positiveWindow: 0.7,
        maxHoldTime: 15,
        kBestPeriod: "15m",
        kBestWindow: [1, 5],
        tpSlCalcMode: "closedK",
        preferredOrderCount: 2,
        secondOrderCustomEnabled: false,
        secondLeverage: 5,
        secondPositionRatio: 40,
        secondMaxPosition: 40000,
        secondMaxHoldTime: 15,
        secondMLinkEnabled: false,
        secondMLinkValue: 1800,
        secondTpEnabled: true,
        secondTpModeBuy: "ratio",
        secondTpModeSell: "ratio",
        secondTpBuyEnabled: true,
        secondTpSellEnabled: true,
        secondTpRatioBuy: 44,
        secondTpRatioSell: 44,
        secondTpFixedBuy: 2,
        secondTpFixedSell: 2,
        secondTpAmpBuy: 25,
        secondTpAmpSell: 25,
        secondSlEnabled: true,
        secondSlModeBuy: "ratio",
        secondSlModeSell: "ratio",
        secondSlBuyEnabled: true,
        secondSlSellEnabled: true,
        secondSlRatioBuy: 85,
        secondSlRatioSell: 85,
        secondSlFixedBuy: 20,
        secondSlFixedSell: 20,
        secondSlAmpBuy: 85,
        secondSlAmpSell: 85,
        secondSingleKMLinkEnabled: false,
        secondSingleKMLinkValue: 1800,
        secondSingleKTpEnabled: true,
        secondSingleKTpModeBuy: 'amp',
        secondSingleKTpModeSell: 'amp',
        secondSingleKTpBuyEnabled: true,
        secondSingleKTpSellEnabled: true,
        secondSingleKTpRatioBuy: 25,
        secondSingleKTpRatioSell: 25,
        secondSingleKTpFixedBuy: 2,
        secondSingleKTpFixedSell: 2,
        secondSingleKTpAmpBuy: 25,
        secondSingleKTpAmpSell: 25,
        secondSingleKSlEnabled: true,
        secondSingleKSlModeBuy: 'fixed',
        secondSingleKSlModeSell: 'fixed',
        secondSingleKSlBuyEnabled: true,
        secondSingleKSlSellEnabled: true,
        secondSingleKSlRatioBuy: 20,
        secondSingleKSlRatioSell: 20,
        secondSingleKSlFixedBuy: 20,
        secondSingleKSlFixedSell: 20,
        secondSingleKSlAmpBuy: 20,
        secondSingleKSlAmpSell: 20,
      },
      withdrawal: {
        withdrawalThreshold: 2088,
        retentionThreshold: 1988,
        alarmThreshold: 5,
      },
    },
  ],
  email: {
    enabled: true,
    sender: "",
    receiver: "",
    smtpServer: "",
    smtpPort: 465,
    password: "",
    minBalance: 5,
    maxConsecutiveLoss: 30000,
  },
  auth: {
    username: "admin",
    password: "Xxxxxx123!",
  },
};
